[feature] configure lambda name & add iam outputs
chanzuckerberg/cztack pull request #230
Opened 2020-09-15 20:50 UTC by michaelmcchen

### Summary
I'm currently refactoring an existing piece of infrastructure to use this lambda module and having the lambda name be configurable would be very helpful so that changes can be updated via a state mv. 

Having the IAM role_name & id be outputs also makes the policy more flexible (the consuming component can then reference the IAM role with a data resource and then add policies). 

### Test Plan
Verified that the Terraform plan (shown below) is as expected. 

```
  # module.heroku-cloudwatch-log-drain.module.lambda.aws_lambda_function.lambda will be created
  + resource "aws_lambda_function" "lambda" {
      + arn                            = (known after apply)
      + filename                       = "../../../../../shared-infra/terraform/modules/heroku-cloudwatch-log-drain/lambda_src/build/package.zip"
      + function_name                  = "heroku-log-drain-czi-connections-main"
      + handler                        = "handle"
      + id                             = (known after apply)
      + invoke_arn                     = (known after apply)
      + last_modified                  = (known after apply)
      + memory_size                    = 128
      + publish                        = false
      + qualified_arn                  = (known after apply)
      + reserved_concurrent_executions = -1
      + role                           = (known after apply)
      + runtime                        = "ruby2.5"
      + source_code_hash               = "EZlLyFz3VTf5pZdvCGR0aC49SOLOG6F4EvpDesaq+2A="
      + source_code_size               = (known after apply)
      + tags                           = {
          + "Name"      = "heroku-log-drain-czi-connections-main"
          + "env"       = "dev"
          + "managedBy" = "terraform"
          + "owner"     = "infra-eng@chanzuckerberg.com"
          + "service"   = "czi-connections-main"
        }
      + timeout                        = 15
      + version                        = (known after apply)

      + environment {
          + variables = {
              + "cloudwatch_log_group_name" = "/heroku-logs/czi-connections-main"
              + "heroku_log_drain_token"    = [redacted]
            }
        }

      + tracing_config {
          + mode = (known after apply)
        }
    }
```

### References
(Optional) Additional links to provide more context.

2020-09-15 21:55 UTC, michaelmcchen commented
Hmm, the aws-aurora-postgres test seems to be broken. 
```
 Error: error creating RDS cluster: InvalidParameterCombination: Cannot find version 11.7 for aurora-postgresql
```
I believe 11.7 is supported by AWS though?

2020-09-16 18:45 UTC, ryanking approved these changes

2020-09-16 18:45 UTC, ryanking commented on aws-lambda-function/main.tf
> +    Name      = var.function_name
This seems the same logic as above.

2020-09-16 18:45 UTC, ryanking commented on aws-lambda-function/variables.tf
> +  type    = string
Add a description which documents the behavior ("if not set...").

2020-09-16 18:46 UTC, ryanking requested changes
meant to mark "request changes"

2020-09-18 21:01 UTC, ryanking approved these changes

2020-09-18 21:47 UTC, merged