[Feature] Add aws-redis-replication-group
chanzuckerberg/cztack pull request #267
Opened 2020-12-10 01:09 UTC by davidrissato

### Summary
This module is similar to [aws-redis-node](https://github.com/chanzuckerberg/cztack/tree/main/aws-redis-node), however it creates a Elasticache Redis cluster using a replication group.
The motivation to create this module is because encryption options (in-transit and at rest) are only available when you create your cluster using a replication group.

### Test Plan
- Manual tests
- (working on unit tests)

### References
(Optional) Additional links to provide more context.

2020-12-23 19:44 UTC, cziie commented on aws-redis-replication-group/outputs.tf
> +output "primary_endpoint_address" {
📝 **[tflint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`primary_endpoint_address` output has no description

2020-12-23 19:44 UTC, cziie commented on aws-redis-replication-group/outputs.tf
> +output "configuration_endpoint_address" {
📝 **[tflint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`configuration_endpoint_address` output has no description

2020-12-23 19:44 UTC, cziie commented on aws-redis-replication-group/outputs.tf
> +output "port" {
📝 **[tflint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`port` output has no description

2021-01-06 19:24 UTC, ryanking requested changes
This module needs to be added to [the list in the ci.yml](https://github.com/chanzuckerberg/cztack/blob/davidrc/redis-replication-group/.github/workflows/ci.yml#L74) in order to run the tests in CI.

2021-01-08 18:44 UTC, ryanking approved these changes

2021-01-08 18:45 UTC, merged